### ISSUE TITLE
Error when plotting course that is not in the local directory

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#128]
```
└─ reckoner plot hack/kind/course.yaml
Traceback (most recent call last):
  File "cli.py", line 4, in <module>
  File "click/core.py", line 764, in __call__
  File "click/core.py", line 717, in main
  File "click/core.py", line 1137, in invoke
  File "click/core.py", line 956, in invoke
  File "click/core.py", line 555, in invoke
  File "click/decorators.py", line 17, in new_func
  File "reckoner/cli.py", line 53, in plot
  File "reckoner/reckoner.py", line 92, in __init__
  File "reckoner/course.py", line 56, in __init__
  File "yaml/__init__.py", line 114, in load
  File "yaml/constructor.py", line 41, in get_single_data
  File "yaml/composer.py", line 36, in get_single_node
  File "yaml/composer.py", line 55, in compose_document
  File "yaml/composer.py", line 84, in compose_node
  File "yaml/composer.py", line 127, in compose_mapping_node
  File "yaml/parser.py", line 98, in check_event
  File "yaml/parser.py", line 428, in parse_block_mapping_key
  File "yaml/scanner.py", line 116, in check_token
  File "yaml/scanner.py", line 223, in fetch_more_tokens
  File "yaml/scanner.py", line 579, in fetch_value
yaml.scanner.ScannerError: mapping values are not allowed here
  in "hack/kind/course.yaml", line 2, column 23
[10376] Failed to execute script cli
```

Does the same when I use `./hack/kind/course.yml`

```
└─ reckoner version
1.4.0
└─ helm version
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
```

**Comment by sudermanjr** [comment]
I'm dumb.  Yaml issue
