### ISSUE TITLE
Linux OS version specific `reckoner` binary import `urllib3` error

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#196]
Not present for OSX or for ~Ubuntu 18.x.x as tested.~ Just reported in 18.x.x

When a binary installation of reckoner is run using a `$KUBECONFIG` that relies on the `aws` command for authentication an import error is thrown by the `aws` command. Running the `aws` command works as expected, when it is run by a `helm` command it works as expected,  but when it is run by a `reckoner` binary it errors out. When run by a `pip` installed `reckoner` command, it works as expected.

So far this has primarily been observed on a fork of Ubuntu 19.x.x but it has also been reported on Fedora.

Minimum steps to reproduce

* Fresh linux
* apt-get install awscli
* pip3 install awscli (without this step, it will throw a segfault instead)
* Install reckoner, helm via the latest binary
* Configure your aws credentials (Reproduced with aws-vault and static keys)
* running cluster and kubeconfig using `aws eks get-token` command for auth
* course.yml
* `reckoner plot` command

```
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --cluster-name
      - cluster.name.com
      command: aws
      env: null
```
Tested command and error:
```
vagrant@ubuntu-eoan:~/test$ reckoner plot course.yml --heading rbac-manager --dry-run --debug
2020-04-14 22:16:45 ubuntu-eoan root[20944] WARNING The --debug flag will be deprecated.  Please use --helm-args or --dry-run instead.
2020-04-14 22:16:46 ubuntu-eoan root[20944] INFO Found Helm Version 2.14.3
2020-04-14 22:16:46 ubuntu-eoan root[20944] ERROR Command Failed with output below:
STDOUT: Client: v2.14.3+g0e7f3b6

STDERR: Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python3.7/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.7/dist-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/usr/local/lib/python3.7/dist-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/lib/python3.7/dist-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.7/dist-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.7/dist-packages/botocore/awsrequest.py", line 25, in <module>
    import botocore.utils
  File "/usr/local/lib/python3.7/dist-packages/botocore/utils.py", line 31, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.7/dist-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py)
Error: Get https://api.staging.internal.reactiveops.com/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: getting credentials: exec: exit status 1

COMMAND: helm version --short
⛵🔥 Encountered errors while reading course file ⛵🔥
Helm Client Failed to initialize: Could not detect helm version
```
Tested OS information:
```
NAME="Ubuntu"
VERSION="19.10 (Eoan Ermine)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.10"
VERSION_ID="19.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
```

**Comment by ejether** [comment]
Also reproduced in Ubuntu Bionic docker image: `quay.io/fairwinds/utilities:v4.4.0`
``` 
sbin/ srv/  sys/
root@52ba615caf73:~# lsb_release
No LSB modules are available.
root@52ba615caf73:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

I exported aws credentials, added a kubeconfig, used reckoner and got the same error
`aws-cli/1.18.39 Python/3.6.9 Linux/4.19.76-linuxkit botocore/1.15.39`

```
reckoner plot course.yml --dry-run --debug
2020-04-15 14:36:16 52ba615caf73 root[221] WARNING The --debug flag will be deprecated.  Please use --helm-args or --dry-run instead.
2020-04-15 14:36:17 52ba615caf73 root[221] INFO Found Helm Version 2.14.3
2020-04-15 14:36:17 52ba615caf73 root[221] ERROR Command Failed with output below:
STDOUT: Client: v2.14.3+g0e7f3b6

STDERR: Traceback (most recent call last):
  File "/usr/local/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/local/lib/python3.6/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/usr/local/lib/python3.6/dist-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/usr/local/lib/python3.6/dist-packages/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/local/lib/python3.6/dist-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/local/lib/python3.6/dist-packages/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/local/lib/python3.6/dist-packages/botocore/awsrequest.py", line 25, in <module>
    import botocore.utils
  File "/usr/local/lib/python3.6/dist-packages/botocore/utils.py", line 31, in <module>
    import botocore.httpsession
  File "/usr/local/lib/python3.6/dist-packages/botocore/httpsession.py", line 8, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl'
Error: Get https://api.staging.internal.reactiveops.com/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: getting credentials: exec: exit status 1

COMMAND: helm version --short
⛵🔥 Encountered errors while reading course file ⛵🔥
Helm Client Failed to initialize: Could not detect helm version
```

**Comment by ejether** [comment]
More fun. 
I cloned and did a binary build of reckoner from master in the utilities container I tested in above and it works without error.

**Comment by bambash** [comment]
I can confirm that building the binary locally bypasses the issue

**Comment by microcosem** [comment]
I can confirm that on Fedora 31 using `pip install` for `reckoner` also bypasses the issue.

**Comment by sudermanjr** [comment]
So the question is, if we build in Ubuntu, will it break anywhere else? Will that solve the issue? 

EJ, Can you give microcosem and bambash a copy of the binary you built in the utilities container?

**Comment by ejether** [comment]
microcosem tried the container build binary on their Fedora installation and still ran in to an error 

At this point I need to suspend my troubleshooting efforts. The current most effective workaround is to install with pip instead of the binary installation on Linux. I'll add a note to the onboarding docs.
