### ISSUE TITLE
Reckoner SchemaValidationError when `context` is used in a `chart` block

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#276]
Chart level `context` field not supported.  
Maybe this has never worked? It seems like it may be a bad idea and that namespace is the better way to do it?

I propose we drop support for context at the chart level instead of adding it to the schema.

Chart declaration:
```
  redis-one:
    context: foo
    namespace: ${namespace}
    namespace_management:
      metadata:
        annotations:
          SpecialAnnotation: forRedisOne
    chart: redis
    repository: bitnami
```

Results in error: 
```
⛵🔥 Encountered errors while reading course file ⛵🔥
Course file has schema validation errors. Please see the docs on schema validation or --log-level debug for in depth validation output.

(Err: Problem Parsing Chart Schema) Additional properties are not allowed ('context' was unexpected).
2021-01-24 14:40:17 C02DG0SRMD6R root[89096] DEBUG Traceback (most recent call last):
  File "/Users/eetherington/code/ejether/reckoner/reckoner/cli.py", line 108, in plot
    validate_course_file(course_file_stream)
  File "/Users/eetherington/code/ejether/reckoner/reckoner/schema_validator/course.py", line 60, in validate_course_file
    raise SchemaValidationError(
reckoner.exception.SchemaValidationError: Course file has schema validation errors. Please see the docs on schema validation or --log-level debug for in depth validation output.

(Err: Problem Parsing Chart Schema) Additional properties are not allowed ('context' was unexpected).
```

**Comment by sudermanjr** [comment]
I didn't think we ever supported that, so yeah, I'm good with dropping support.

**Comment by ejether** [comment]
👍 Agreed. 

The Chart code does some gymnastics to use the course default context but allow overriding at the chart level in the same way that `namespace` does so there is code to remove and simplify.
