### ISSUE TITLE
Golang version panics when no kubeconfig is present

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#482]

**Comment by sudermanjr** [comment]
```  
▶ ./reckoner-go template end_to_end_testing/course_files/01_test_basic.yml -o farglebargle -v10 
I1005 08:05:18.594215   48719 course.go:253] did not detect v2 course file - trying conversion from v1
I1005 08:05:18.594356   48719 course.go:258] WARNING: this course file was automatically converted from v1 to v2 - this functionality may be removed in the future
I1005 08:05:18.594364   48719 course.go:307] no default repository set - skipping filling out defaults
I1005 08:05:18.594389   48719 helm.go:37] found helm at /Users/asuderma/.asdf/shims/helm
I1005 08:05:18.594396   48719 client.go:113] no minimum helm version found, assuming okay
I1005 08:05:18.594399   48719 client.go:136] no minimum reckoner version found, assuming okay
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d6a44d]

goroutine 1 [running]:
github.com/fairwindsops/reckoner/cmd.glob..func3(0x2b45400, {0xc000351600, 0x4, 0x4})
        /Users/asuderma/go/src/github.com/fairwindsops/reckoner/cmd/root.go:106 +0xcd
github.com/spf13/cobra.(*Command).execute(0x2b45400, {0xc0003515c0, 0x4, 0x4})
        /Users/asuderma/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x2b44f00)
        /Users/asuderma/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/asuderma/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/fairwindsops/reckoner/cmd.Execute({0x2158200, 0x0}, {0x2175420, 0xc0000001a0})
        /Users/asuderma/go/src/github.com/fairwindsops/reckoner/cmd/root.go:169 +0x7e
main.main()
        /Users/asuderma/go/src/github.com/fairwindsops/reckoner/main.go:29 +0x35
        ```

**Comment by sudermanjr** [comment]
I was mistaken. Wrong error
