### ISSUE TITLE
Local file charts should not try to `helm repo add`

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#54]
If a path is specified as the repository, we see this warning which is confusing:
```
✔ ± reckoner plot course.yml --heading ip-masq-agent --dry-run
2019-01-25 09:36:19 root[36831]     INFO Installing ip-masq-agent
2019-01-25 09:36:20 root[36831]  WARNING Unable to install repository ../../../../../charts: Command Failed with output below:
STDOUT:
STDERR: Error: Could not find protocol handler for:

COMMAND: helm repo add ../../../../../charts None
2019-01-25 09:36:21 root[36831]     INFO [debug] Created tunnel using local port: '51041'

[debug] SERVER: "127.0.0.1:51041"
```

I believe we shouldn't be trying to do a `helm repo add` if the "repository" is a local file.

**Comment by lucasreed** [comment]
I'm re-opening this because I think this needs to be functional. We have a local chart we want to install and it is the same behavior seen above.

```reckoner plot course.yml --heading fluentd-gelf
2020-04-01 09:22:48 Lukes-MacBook-Pro.local root[11895] INFO Found Helm Version 3.1.2
2020-04-01 09:22:52 Lukes-MacBook-Pro.local root[11895] INFO Installing fluentd-gelf
2020-04-01 09:22:53 Lukes-MacBook-Pro.local root[11895] WARNING Unable to install repository ../../../../../charts: Command Failed with output below:
STDOUT:
STDERR: Error: could not find protocol handler for:

COMMAND: helm repo add ../../../../../charts None
Traceback (most recent call last):
  File "reckoner/course.py", line 180, in install_charts
  File "reckoner/chart.py", line 285, in install
  File "reckoner/chart.py", line 256, in install
  File "reckoner/repository.py", line 80, in install
  File "reckoner/repository.py", line 77, in install
  File "reckoner/helm/client.py", line 173, in repo_add
  File "reckoner/helm/client.py", line 125, in execute
reckoner.helm.client.HelmClientException: Command Failed with output below:
STDOUT:
STDERR: Error: could not find protocol handler for:

COMMAND: helm repo add ../../../../../charts None

2020-04-01 09:22:53 Lukes-MacBook-Pro.local root[11895] ERROR Helm upgrade failed on fluentd-gelf
2020-04-01 09:22:53 Lukes-MacBook-Pro.local root[11895] ERROR ERROR: Chart failed to install.
2020-04-01 09:22:53 Lukes-MacBook-Pro.local root[11895] ERROR  - fluentd-gelf
2020-04-01 09:22:53 Lukes-MacBook-Pro.local root[11895] ERROR Stopping chart installations due to an error! Some of your charts may not have been installed!
2020-04-01 09:22:53 Lukes-MacBook-Pro.local root[11895] ERROR Not running Course post_install hook due to a chart install error!
⛵🔥 Encountered errors while running the course ⛵🔥

* * * * *

Chart Name: fluentd-gelf
Status: Failed
Error Reason: Command Failed with output below:
STDOUT:
STDERR: Error: could not find protocol handler for:

COMMAND: helm repo add ../../../../../charts None```

**Comment by sudermanjr** [comment]
@lucasreed  Can you share the course snippet that is causing the error?

**Comment by lucasreed** [comment]
```
  fluentd-gelf:
    repository: ../../../../../charts
    set-values:
      image: REDACTED
      gelfHost: REDACTED
      encoding: true
      s3:
        enabled: false
      resources:
        limits:
          memory: 550Mi
        requests:
          memory: 550Mi
```

I redacted customer information. I only assume this ever actually worked to be honest. It's possible it didn't, so maybe this is a clarification question. It's something that's been around for a while I think.
